import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Card from "../components/card";

export default function Home() {

  const handleOnBannerBtnClick = () => {
    console.log('banner')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
        <Card name='DarkHorse Coffee' href='/coffee-store/darkhorse-coffee' imgUrl='' />
      </main>
    </div>
  )
}
