import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Card from "../components/card";
import img from '../public/vercel.svg'
import coffeeStoresData from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData
    }
  }
}

export default function Home(props) {
  const handleOnBannerBtnClick = () => {
    console.log('banner')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map(coffeeStore => (
                  <Card
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    href={`coffee-store/${coffeeStore.id}`}
                    imgUrl={coffeeStore.imgUrl}
                    className={styles.card}
                  />
                ))
              }
            </div>
          </>
        )}
      </main>
    </div>
  )
}
